services:
  client:
    environment:
      - PORT=3000
    image: ${DOCKER_REGISTRY-}client
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "3000:3000"
